### ISSUE TITLE
Run on top of UDP?

### ISSUE THREAD

**Issue by jbenet** [tcpexmachina/remy#22]
I want to run a Remy-optimized TCP stack in a widel-deployed application. We could do this on top of UDP-- as most  non-TCP transport protocols operate now. 
- Do you foresee any problems with this? 
- What would be the easiest route?
- Would anyone else be interested?

**Comment by keithw** [comment]
I don't think we're quite ready to run Remy-designed protocols over the real Internet without a lot more development effort. Of course you are welcome to try!

**Comment by jbenet** [comment]
@keithw could you unpack that for us? what's missing; what do we need to do? (the clearer it is the more we can all contribute to the cause)

**Comment by diasdavid** [comment]
I am interest to understand what would be the next steps to achieve that. Is there a roadmap currently available? Thank you.

**Comment by keithw** [comment]
We now have a shim that runs RemyCCs over UDP in our Pantheon project: http://pantheon.stanford.edu
