### ISSUE TITLE
Make Error - sender-logger.cc

### ISSUE THREAD

**Issue by dhineshn** [tcpexmachina/remy#48]
![screenshot from 2016-09-14 22-20-26](https://cloud.githubusercontent.com/assets/22203947/18528520/a2fed0f2-7ac9-11e6-9977-35aad8695b79.png)

**Comment by keithw** [comment]
We need more information to diagnose this -- what operating system, version, and compiler version are you using? What arguments (if any) did you give to `./configure` ?

Just verified that it builds on Ubuntu 16.04 LTS with g++ 5.4.0. It also builds on Ubuntu 14.04 LTS in the Travis-CI virtual environment described in the `.travis.yml` file (with g++ 4.9).

**Comment by dhineshn** [comment]
Works fine with g++ 5.4.0
