### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by dwy927** [tcpexmachina/remy#51]
when i compile (make phrase) on this project, compile went wrong, and my operation is  MacOS
`git checkout v0.1`

```
whiskertree.cc:188:10: error: use of undeclared identifier 'accumulate'
  return accumulate( _children.begin(),
         ^
1 error generated.
make[2]: *** [whiskertree.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```
thanks

**Comment by keithw** [comment]
We think this was fixed in November on the master branch (in commit 9a29ae95559c65b6f39275dad9e4690b35019639). Is there a particular reason you are using v0.1?
