### ISSUE TITLE
Does Remy Hold-Up in Production?

### ISSUE THREAD

**Issue by victorstewart** [tcpexmachina/remy#55]
the website speaks of hoping that Remy performs in real world cases as it does in the simulations... but I assume by now real world test cases have been done? Is anyone using Remy derived CC algorithms in production?

**Comment by keithw** [comment]
See https://pantheon.stanford.edu for some frequent real-world measurements of one Remy-designed congestion-control scheme (the "Tao-100x" scheme from our 2014 "Learnability" paper) and some newer computer-generated or learned schemes ("Indigo", "Muses", etc.). The short answer is no, nobody is using them in production... yet at least. We are using some real-world learning in a related project (https://puffer.stanford.edu) though.

**Comment by victorstewart** [comment]
interesting reads.

RE the challenges of simulating... you should speak with some dynamical systems specialists in the math department, because the traffic follows such natures: deterministic with random kernels.

**Comment by victorstewart** [comment]
https://www.quantamagazine.org/math-proof-finds-all-change-is-mix-of-order-and-randomness-20190327/
